Repository getlift/lift, pull requests merged in 2021-06, with the labels that each got.

#28 Queue: add CLI commands to manage SQS dead letter queues
  docs/queue.md
  package-lock.json
  package.json
  src/classes/AwsProvider.ts
  src/classes/aws.ts
  src/constructs/Queue.ts
  src/constructs/queue/sqs.ts
  src/utils/sleep.ts
  test/unit/queues.test.ts
  test/unit/staticWebsites.test.ts
  test/utils/mockAws.ts
Labels: enhancement

#32 Fix typo in SQS publisher function example
  docs/queue.md
Labels: documentation

#33 Typo fix in queue docs
  docs/queue.md
Labels: documentation

#37 Fixed typo on “construct“ variables (fixes #36)
  docs/storage.md
  docs/webhook.md
Labels: documentation

#39 Added missing "type" configuration for webhooks
  README.md
  docs/webhook.md
Labels: documentation

#46 Fix node10 compatibility
  src/constructs/StaticWebsite.ts
  src/plugin.ts
  src/utils/s3-sync.ts
  tsconfig.json
Labels: bug

#45 Separate user errors from bugs in the CLI output and telemetry
  src/constructs/StaticWebsite.ts
  src/constructs/Webhook.ts
  src/plugin.ts
  src/utils/error.ts
Labels: enhancement

#49 fix: allow to use the new provider.iam.role.statements
  src/plugin.ts
  test/fixtures/permissions/serverless.yml
  test/fixtures/permissions/worker.js
  test/unit/permissions.test.ts
Labels: bug

#50 Instantiate constructs after all variables are resolved
  .eslintignore
  .eslintrc
  src/classes/AwsConstruct.ts
  src/classes/AwsProvider.ts
  src/classes/Construct.ts
  src/constructs/Queue.ts
  src/constructs/StaticWebsite.ts
  src/constructs/Storage.ts
  src/constructs/Webhook.ts
  src/plugin.ts
  src/types/serverless.ts
  test/fixtures/variables/extra-plugin.js
  test/fixtures/variables/serverless.yml
  test/unit/common.test.ts
  test/unit/variables.test.ts
Labels: bug

#51 [Static Website] Add new `errorPage` configuration
  docs/static-website.md
  src/constructs/StaticWebsite.ts
  test/unit/staticWebsites.test.ts
Labels: enhancement
